version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always
    networks:
      - mern_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_container
    ports:
      - "5000:5000"
    environment:
      # We override the .env MONGODB_URI here to use the container name
      - MONGODB_URI=mongodb://mongodb:27017/lost-and-found
      - PORT=5000
      - JWT_SECRET=my_super_secret_jwt_key_123
    depends_on:
      - mongodb
    restart: always
    networks:
      - mern_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_container
    ports:
      - "5173:5173"
    environment:
      # This points to localhost because the browser executes this code on the host machine,
      # and it needs to reach the backend exposed on localhost:5000.
      - VITE_API_URL=http://13.48.58.174:5000/api
    depends_on:
      - backend
    restart: always
    networks:
      - mern_network

volumes:
  mongodb_data:

networks:
  mern_network:
    driver: bridge
